spring:
  profiles:
    group:
      local:
        - local-logging
      dev:
        - dev-logging
      prod:
        - prod-logging
    active: local

logging:
  config: classpath:logback/logback.xml
---

spring:
  config:
    activate:
      on-profile: local
---

spring:
  config:
    activate:
      on-profile: dev
---

spring:
  config:
    activate:
      on-profile: prod
