logging:
  level:
    root: debug
    org.hibernate.type: trace

server:
  port: 8080

key:
  jwt:
    secret: ENC(s7eFrh2X8Zllu4Q7M0FqvwDmVaX46+DEEhMFrWn2Jm8X126mKs498wX6Yoy2ie7FsuN25BsPZuo=)

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(YQBtOWS4evW8WsSuEeXUmac1FJ5mPCkvT+0G6/XXMxo=)
    password: ENC(hKwE5NS4+4x7MxPTuqbgQ5G88gJ7R3Tn8OwDx/u5zp4=)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(jj4TSLq5sRKYX6J6gev17ooKBaM+9ILcg4CA8IA7/yOVTe8eLPmRymyKSMxOD82qPNMi/X2sHwj0wZmHc6bSD3Io10o5mRwJ3cOPVXw21KOo8rL3qQ7AAg==)
            client-secret: ENC(+XEqTDlh6OL/ySG9aPm6jtiaW4Ptu9ipjc1ExECS0HO/8oEMtuZZ7kcgDFim/MA+)
            scope: profile, email
          github:
            clientId: ENC(/pAslyQ1X78t4+UDgReoDR9eKMsxkwLWHz3epY1TzMU=)
            clientSecret: ENC(kUbxD1ogPQYKZFf+gfwzgbdxa93O2WJzChRYN4XExZyP2DAGRuRNBChdcgl9EGiThYZq5uqpmG4=)
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/localdb;MODE=MYSQL
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        # 예약어 에러로 인하여, SQL 실행 시 인용 부호로 테이블과 컬럼을 감싸는 옵션 활성화
        globally_quoted_identifiers: true
    show-sql: true
    hibernate:
      ddl-auto: create

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  output:
    ansi:
      enabled: always



