logging:
  level:
    org.hibernate.type: trace

server:
  port: 8080

key:
  jwt:
    secret: ENC(s7eFrh2X8Zllu4Q7M0FqvwDmVaX46+DEEhMFrWn2Jm8X126mKs498wX6Yoy2ie7FsuN25BsPZuo=)

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(jj4TSLq5sRKYX6J6gev17ooKBaM+9ILcg4CA8IA7/yOVTe8eLPmRymyKSMxOD82qPNMi/X2sHwj0wZmHc6bSD3Io10o5mRwJ3cOPVXw21KOo8rL3qQ7AAg==)
            client-secret: ENC(+XEqTDlh6OL/ySG9aPm6jtiaW4Ptu9ipjc1ExECS0HO/8oEMtuZZ7kcgDFim/MA+)
            scope: profile, email
          github:
            clientId: 6a66211ee57c12ed75fa
            clientSecret: d6b0b4876f5d0d138ce0dc65bf97b33b75d53fea
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/localdb;MODE=MYSQL
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        # 예약어 에러로 인하여, SQL 실행 시 인용 부호로 테이블과 컬럼을 감싸는 옵션 활성화
        globally_quoted_identifiers: true
    show-sql: true
    hibernate:
      ddl-auto: create

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  output:
    ansi:
      enabled: always



