logging:
  level:
    org.hibernate.type: trace

server:
  port: 8080

spring:
  datasource:
    url: ENC(ijJF6ccKPFPIydr1qG/KXqRWAOFG6g+7/uRnVs/VFis7WYS9lOd7uCLeV+gTdGbM/L7ic4TsgtuAc/gK5+KkwsQUC/XH8tE3yMzkaPnjxrQPLYa3EfJXjqy1j0v9dtUMja94wdAld41U8HrOnwaifQ5hcesg3cbOV7but30dJmo=)
    username: ENC(H1ob3LGdmEA4FVoShs5leA==)
    password: ENC(kNGFnTZ6jeZndmc2zWI+Ed0PV8nynO42chWbaNr1B5o=)
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        # 예약어 에러로 인하여, SQL 실행 시 인용 부호로 테이블과 컬럼을 감싸는 옵션 활성화
        globally_quoted_identifiers: true
    show-sql: true
    hibernate:
      ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  output:
    ansi:
      enabled: always



